import urllib2

import scrapy
from scrapy.spiders import CrawlSpider, Rule
from scrapydemo.baidubaobao.BaiduBaobaoParser import BaiduBaobaoParser


class BaiduBaobaoSpider(CrawlSpider):
    name = "baidubaobao"
    allowed_domains = ["baobao.baidu.com"]
    start_urls = [
        "http://baobao.baidu.com/browse",
        'http://baobao.baidu.com/browse?pn=20',
        'http://baobao.baidu.com/browse?pn=40',
        'http://baobao.baidu.com/browse?pn=60',
        'http://baobao.baidu.com/browse?pn=80',
        'http://baobao.baidu.com/browse?pn=100',
        'http://baobao.baidu.com/browse?pn=120',
        'http://baobao.baidu.com/browse?pn=140',
        'http://baobao.baidu.com/browse?pn=160',
        'http://baobao.baidu.com/browse?pn=180',
        'http://baobao.baidu.com/browse?pn=200',
        'http://baobao.baidu.com/browse?pn=220',
        'http://baobao.baidu.com/browse?pn=240',
        'http://baobao.baidu.com/browse?pn=260',
        'http://baobao.baidu.com/browse?pn=280',
        'http://baobao.baidu.com/browse?pn=300',
        'http://baobao.baidu.com/browse?pn=320',
        'http://baobao.baidu.com/browse?pn=340',
        'http://baobao.baidu.com/browse?pn=360',
        'http://baobao.baidu.com/browse?pn=380',
        'http://baobao.baidu.com/browse?pn=400',
        'http://baobao.baidu.com/browse?pn=420',
        'http://baobao.baidu.com/browse?pn=440',
        'http://baobao.baidu.com/browse?pn=460',
        'http://baobao.baidu.com/browse?pn=480',
        'http://baobao.baidu.com/browse?pn=500',
        'http://baobao.baidu.com/browse?pn=520',
        'http://baobao.baidu.com/browse?pn=540',
        'http://baobao.baidu.com/browse?pn=560',
        'http://baobao.baidu.com/browse?pn=580',
        'http://baobao.baidu.com/browse?pn=600',
        'http://baobao.baidu.com/browse?pn=620',
        'http://baobao.baidu.com/browse?pn=640',
        'http://baobao.baidu.com/browse?pn=660',
        'http://baobao.baidu.com/browse?pn=680',
        'http://baobao.baidu.com/browse?pn=700',
        'http://baobao.baidu.com/browse?pn=720',
        'http://baobao.baidu.com/browse?pn=740',
        'http://baobao.baidu.com/browse?pn=760',
        'http://baobao.baidu.com/browse?pn=780',
        'http://baobao.baidu.com/browse?pn=800',
        'http://baobao.baidu.com/browse?pn=820',
        'http://baobao.baidu.com/browse?pn=840',
        'http://baobao.baidu.com/browse?pn=860',
        'http://baobao.baidu.com/browse?pn=880',
        'http://baobao.baidu.com/browse?pn=900',
        'http://baobao.baidu.com/browse?pn=920',
        'http://baobao.baidu.com/browse?pn=940',
        'http://baobao.baidu.com/browse?pn=960',
        'http://baobao.baidu.com/browse?pn=980',
        'http://baobao.baidu.com/browse?pn=1000',
        'http://baobao.baidu.com/browse?pn=1020',
        'http://baobao.baidu.com/browse?pn=1040',
        'http://baobao.baidu.com/browse?pn=1060',
        'http://baobao.baidu.com/browse?pn=1080',
        'http://baobao.baidu.com/browse?pn=1100',
        'http://baobao.baidu.com/browse?pn=1120',
        'http://baobao.baidu.com/browse?pn=1140',
        'http://baobao.baidu.com/browse?pn=1160',
        'http://baobao.baidu.com/browse?pn=1180',
        'http://baobao.baidu.com/browse?pn=1200',
        'http://baobao.baidu.com/browse?pn=1220',
        'http://baobao.baidu.com/browse?pn=1240',
        'http://baobao.baidu.com/browse?pn=1260',
        'http://baobao.baidu.com/browse?pn=1280',
        'http://baobao.baidu.com/browse?pn=1300',
        'http://baobao.baidu.com/browse?pn=1320',
        'http://baobao.baidu.com/browse?pn=1340',
        'http://baobao.baidu.com/browse?pn=1360',
        'http://baobao.baidu.com/browse?pn=1380',
        'http://baobao.baidu.com/browse?pn=1400',
        'http://baobao.baidu.com/browse?pn=1420',
        'http://baobao.baidu.com/browse?pn=1440',
        'http://baobao.baidu.com/browse?pn=1460',
        'http://baobao.baidu.com/browse?pn=1480',
        'http://baobao.baidu.com/browse?pn=1500',
        'http://baobao.baidu.com/browse?pn=1520',
        'http://baobao.baidu.com/browse?pn=1540',
        'http://baobao.baidu.com/browse?pn=1560',
        'http://baobao.baidu.com/browse?pn=1580',
        'http://baobao.baidu.com/browse?pn=1600',
        'http://baobao.baidu.com/browse?pn=1620',
        'http://baobao.baidu.com/browse?pn=1640',
        'http://baobao.baidu.com/browse?pn=1660',
        'http://baobao.baidu.com/browse?pn=1680',
        'http://baobao.baidu.com/browse?pn=1700',
        'http://baobao.baidu.com/browse?pn=1720',
        'http://baobao.baidu.com/browse?pn=1740',
        'http://baobao.baidu.com/browse?pn=1760',
        'http://baobao.baidu.com/browse?pn=1780',
        'http://baobao.baidu.com/browse?pn=1800',
        'http://baobao.baidu.com/browse?pn=1820',
        'http://baobao.baidu.com/browse?pn=1840',
        'http://baobao.baidu.com/browse?pn=1860',
        'http://baobao.baidu.com/browse?pn=1880',
        'http://baobao.baidu.com/browse?pn=1900',
        'http://baobao.baidu.com/browse?pn=1920',
        'http://baobao.baidu.com/browse?pn=1940',
        'http://baobao.baidu.com/browse?pn=1960',
        'http://baobao.baidu.com/browse?pn=1980'
    ]
    rules = [
        Rule(scrapy.linkextractors.LinkExtractor(allow=('http://baobao.baidu.com/question/.*.html',),),
             follow=True, callback="parse_detail"),

    ]

    def parse_detail(self, response):
        parser = BaiduBaobaoParser()
        return parser.parse_detail_page(response)
